/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.timejogadoresmaven;

import DAO.TimeDAO;
import java.util.List;
import MODEL.Time;
import CONEXAO.ConexaoBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane; // Para exibir mensagens

/**
 *
 * @author gabir
 */
public class criarJogadorFrame extends javax.swing.JFrame {

    /**
     * Creates new form criarJogadorFrame
     */
    public criarJogadorFrame(){
        this.setTitle("Criar Jogador");
        initComponents();
        loadTimes();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    private void loadTimes() {
        try {
            // Crie uma conexão com o banco de dados
            Connection connection = ConexaoBD.getConnection();

            // Crie uma instância de TimeDAO com a conexão
            TimeDAO timeDAO = new TimeDAO(connection);

            // Chame o método read() da instância timeDAO
            List<Time> times = timeDAO.read();

            jComboBoxTime.removeAllItems();
            if (times.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nenhum time encontrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                for (Time time : times) {
                    jComboBoxTime.addItem(time.getNome());
                }
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Exibe o stack trace do erro
            JOptionPane.showMessageDialog(this, "Erro ao carregar times: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeTextField = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jLabelNacionalidade = new javax.swing.JLabel();
        nacionalidadeTextField = new javax.swing.JTextField();
        jLabelTime = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        posicaoTextField = new javax.swing.JTextField();
        jLabelNacionalidade1 = new javax.swing.JLabel();
        jComboBoxTime = new javax.swing.JComboBox<>();
        idadejLabel = new javax.swing.JLabel();
        alturaTextField = new javax.swing.JTextField();
        idadeSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome");

        jLabelAltura.setText("Altura");

        jLabelNacionalidade.setText("Nacionalidade");

        nacionalidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadeTextFieldActionPerformed(evt);
            }
        });

        jLabelTime.setText("Time");

        jButton1.setText("Criar Jogador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        posicaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoTextFieldActionPerformed(evt);
            }
        });

        jLabelNacionalidade1.setText("Posição");

        jComboBoxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTimeActionPerformed(evt);
            }
        });

        idadejLabel.setText("Idade");

        alturaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nacionalidadeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posicaoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jLabelNacionalidade1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idadejLabel)
                            .addComponent(idadeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTime)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNacionalidade)
                            .addComponent(jLabelAltura)
                            .addComponent(jLabelNacionalidade1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nacionalidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(posicaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idadejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(idadeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void nacionalidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadeTextFieldActionPerformed

    private void posicaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicaoTextFieldActionPerformed

    private void jComboBoxTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTimeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 // Captura os dados dos campos de entrada
String nome = nomeTextField.getText();
int idade = (Integer) idadeSpinner.getValue(); // Captura o valor do JSpinner
String posicao = posicaoTextField.getText();
String nacionalidade = nacionalidadeTextField.getText();
String alturaTexto = alturaTextField.getText(); // Armazena o texto da altura
String timeNome = (String) jComboBoxTime.getSelectedItem(); // Nome do time selecionado

// Verifica se o campo de idade é válido
if (idade <= 0) {
    JOptionPane.showMessageDialog(this, "Por favor, insira uma idade válida.", "Erro", JOptionPane.ERROR_MESSAGE);
    return; // Sai do método
}

// Verifica se o campo de altura está vazio
if (alturaTexto.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor, insira a altura.", "Erro", JOptionPane.ERROR_MESSAGE);
    return; // Sai do método
}

double altura;

try {
    // Converte altura apenas após a validação
    altura = Double.parseDouble(alturaTexto); // Converte o texto da altura para Double
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Por favor, insira um valor numérico válido para a altura.", "Erro", JOptionPane.ERROR_MESSAGE);
    return; // Sai do método
}

// Usando a classe de conexão ConexaoBD
try (Connection conn = ConexaoBD.getConnection()) {
    // Prepara a instrução SQL para inserção
    String sql = "INSERT INTO jogadores (nome, idade, posicao, nacionalidade, altura, time_nome) VALUES (?, ?, ?, ?, ?, ?)"; 
    PreparedStatement pstmt = conn.prepareStatement(sql);

    // Define os valores para os parâmetros da instrução SQL
    pstmt.setString(1, nome);
    pstmt.setInt(2, idade);
    pstmt.setString(3, posicao);
    pstmt.setString(4, nacionalidade);
    pstmt.setDouble(5, altura);
    pstmt.setString(6, timeNome); // Utiliza o nome do time selecionado

    // Executa a inserção
    pstmt.executeUpdate();

    // Notifica que o jogador foi adicionado
    JOptionPane.showMessageDialog(this, "Jogador adicionado com sucesso!");
    TimeJogadoresMaven tabelaJogadores = new TimeJogadoresMaven();
    tabelaJogadores.loadJogadores(); // Atualiza a tabela com os novos dados
    
    // Limpa os campos após a inserção
    nomeTextField.setText("");
    idadeSpinner.setValue(0); // Reseta o JSpinner para o valor padrão
    posicaoTextField.setText("");
    nacionalidadeTextField.setText("");
    alturaTextField.setText(""); // Limpa o campo de altura
    jComboBoxTime.setSelectedIndex(0); // Reseta o JComboBox para o primeiro item

    // Oculta a janela atual
    this.setVisible(false);
    tabelaJogadores.loadJogadores(); // Atualiza a tabela com os novos dados
} catch (SQLException e) {
    // Exibe uma mensagem de erro em caso de falha
    JOptionPane.showMessageDialog(this, "Erro ao adicionar jogador: " + e.getMessage());
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
     // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    private void alturaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(criarJogadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(criarJogadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(criarJogadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(criarJogadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alturaTextField;
    private javax.swing.JSpinner idadeSpinner;
    private javax.swing.JLabel idadejLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxTime;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelNacionalidade;
    private javax.swing.JLabel jLabelNacionalidade1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nacionalidadeTextField;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField posicaoTextField;
    // End of variables declaration//GEN-END:variables
}
